export const ActionTypes = {
  DO_LOGIN_REQUEST: 'DO_LOGIN_REQUEST',
  DO_LOGIN_SUCCESS: 'DO_LOGIN_SUCCESS',
  DO_LOGIN_ERROR: 'DO_LOGIN_ERROR',

  API_ERROR: 'API_ERROR',
  DO_USER_LOGOUT: 'DO_USER_LOGOUT',

  DO_SEARCH_REQUEST: 'DO_SEARCH_REQUEST',
  DO_SEARCH_SUCCESS: 'DO_SEARCH_SUCCESS',
};
